[hekad]
maxprocs = 1

#[ProcStats]
#type = "FilePollingInput"
#ticker_interval = 1
#file_path = "/proc/stat"
#decoder = "ProcStatDecoder"

#[ProcStatDecoder]
#type = "SandboxDecoder"
#filename = "lua_decoders/linux_procstat.lua"

#[MemStats]
#type = "FilePollingInput"
#ticker_interval = 1
#file_path = "/proc/meminfo"
#decoder = "MemStatsDecoder"

#[MemStatsDecoder]
#type = "SandboxDecoder"
#filename = "lua_decoders/linux_memstats.lua"

[DockerEventInput]
type = "DockerEventInput"

#[input]
#type = "LogstreamerInput"
#log_directory = "/var/lib/docker/containers"
#file_match = '(?P<Container>[^/]+)/[a-zA-Z0-9]+-json.log'
#priority = ["^Index"]
#differentiator = ["Container"]

#[DockerLogsInput]
#type = "DockerLogInput"
#decoder = "RegexDecoder"
#can_exit = true


#[MultiDecoder]
#type = "MultiDecoder"
#subs = ['JsonDecoder', 'RegexDecoder']
#subs = ['RegexDecoder']
#cascade_strategy = "first-wins"
#log_sub_errors = true


#[JsonDecoder]
#type = "SandboxDecoder"
#filename = "lua_decoders/json.lua"
#
#    [JsonDecoder.config]
#    payload_keep = true
#    map_fields = true

[RegexDecoder]
type = "PayloadRegexDecoder"
match_regex = "(?P<message>.*)"

	[RegexDecoder.message_fields]
	message = "%message%"

#[dockerConfig]
#type = "LogstreamerInput"
#log_directory = "/var/lib/docker/containers"
#file_match = '(?P<Container>[^/]+)/config(.v2)?.json'
#differentiator = ["Container", "-config"]
#splitter = "NullSplitter"

[HttpListenInput]
address = "0.0.0.0:8325"
decoder = "K8s_monitor"

[K8s_monitor]
type = "SandboxDecoder"
filename = "lua_decoders/json.lua"

    [K8s_monitor.config]
    type = "K8s_monitor"
    payload_keep = false
    map_fields = true

[DashboardOutput]
ticker_interval = 30

[ESJsonEncoder]
index = "heka-%{Type}-%{%Y.%m.%d}"
es_index_from_timestamp = true
type_name = "%{Type}"
    [ESJsonEncoder.field_mappings]
    Timestamp = "@timestamp"

[ElasticSearchOutput]
message_matcher = "Type != ''"
server = "http://elasticsearch:9200"
encoder = "ESJsonEncoder"
flush_interval = 50
