# Not built
elasticsearch:
  image: index.alauda.cn/library/elasticsearch:latest
  ports:
    - "9200:9200"

logstash:
  build: logstash/
  ports:
    - "5000:5000"
  links:
    - elasticsearch

collectd:
  hostname: collectd01
  domainname: collectd01.com
  image: index.alauda.cn/library/elasticsearch:latest
  privileged: true
  ports:
   - "25826:25826/udp"
  links:
   - logstash
  environment:
   - INFLUXDB_SERVER=logstash
   - INFLUXDB_PORT=25826

kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
