# Not built
elasticsearch:
  image: index.alauda.cn/library/elasticsearch
  ports:
    - 9200:9200

logstash:
  build: logstash/
  ports:
    - "5000:5000"
  links:
    - elasticsearch

collectd:
  hostname: collectd01
  domainname: collectd01.com
  image:  index.alauda.cn/asiainfoldp/collectd-new 
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  
  ports:
   - "25826:25826/udp"
  links:
   - logstash
  environment:
   - INFLUXDB_SERVER=logstash
   - INFLUXDB_PORT=25826
heka:
  hostname: heka01
  domainname: heka01.com
  image: index.alauda.cn/asiainfoldp/docker-heka
  privileged: true
  volumes:
    - ./config.toml:/app/config.toml
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - elasticsearch
  ports:
    - "8325:8325"
  
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
